//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATD_DATA
    {
        public Nullable<int> COUNTER0 { get; set; }
        public int COUNTER { get; set; }
        public Nullable<int> LPUIN { get; set; }
        public Nullable<int> FIO_COUNTER { get; set; }
        public Nullable<int> FIO_LPUIN { get; set; }
        public byte[] DATA_FILE { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string OPERATOR { get; set; }
        public byte[] DATA_FILE_2 { get; set; }
    }
}
