//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATS_REPORT_PARAM
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<long> DATA_COUNTER { get; set; }
        public Nullable<int> DATA_LPUIN { get; set; }
        public string NAME { get; set; }
        public string VALUE { get; set; }
    }
}
