//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DATAEntities : DbContext
    {
        public DATAEntities()
            : base("name=DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DATD_DATA> DATD_DATA { get; set; }
        public DbSet<DATS_REPORT_PARAM> DATS_REPORT_PARAM { get; set; }
    
        public virtual ObjectResult<MC_BROWSE_CLIENT_PHOTO_Result> MC_BROWSE_CLIENT_PHOTO(Nullable<long> counter0_fio, Nullable<int> lpuin_fio)
        {
            var counter0_fioParameter = counter0_fio.HasValue ?
                new ObjectParameter("counter0_fio", counter0_fio) :
                new ObjectParameter("counter0_fio", typeof(long));
    
            var lpuin_fioParameter = lpuin_fio.HasValue ?
                new ObjectParameter("lpuin_fio", lpuin_fio) :
                new ObjectParameter("lpuin_fio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MC_BROWSE_CLIENT_PHOTO_Result>("MC_BROWSE_CLIENT_PHOTO", counter0_fioParameter, lpuin_fioParameter);
        }
    
        public virtual ObjectResult<MC_BROWSE_CLIENT_PROFILE_Result> MC_BROWSE_CLIENT_PROFILE(Nullable<long> counter0_credit, Nullable<int> lpuin_credit, string kod_otdeleniya)
        {
            var counter0_creditParameter = counter0_credit.HasValue ?
                new ObjectParameter("counter0_credit", counter0_credit) :
                new ObjectParameter("counter0_credit", typeof(long));
    
            var lpuin_creditParameter = lpuin_credit.HasValue ?
                new ObjectParameter("lpuin_credit", lpuin_credit) :
                new ObjectParameter("lpuin_credit", typeof(int));
    
            var kod_otdeleniyaParameter = kod_otdeleniya != null ?
                new ObjectParameter("kod_otdeleniya", kod_otdeleniya) :
                new ObjectParameter("kod_otdeleniya", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MC_BROWSE_CLIENT_PROFILE_Result>("MC_BROWSE_CLIENT_PROFILE", counter0_creditParameter, lpuin_creditParameter, kod_otdeleniyaParameter);
        }
    
        public virtual ObjectResult<MC_BROWSE_PKO_Result> MC_BROWSE_PKO(Nullable<long> counter0_payment, Nullable<int> lpuin_payment, string kod_otdeleniya)
        {
            var counter0_paymentParameter = counter0_payment.HasValue ?
                new ObjectParameter("counter0_payment", counter0_payment) :
                new ObjectParameter("counter0_payment", typeof(long));
    
            var lpuin_paymentParameter = lpuin_payment.HasValue ?
                new ObjectParameter("lpuin_payment", lpuin_payment) :
                new ObjectParameter("lpuin_payment", typeof(int));
    
            var kod_otdeleniyaParameter = kod_otdeleniya != null ?
                new ObjectParameter("kod_otdeleniya", kod_otdeleniya) :
                new ObjectParameter("kod_otdeleniya", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MC_BROWSE_PKO_Result>("MC_BROWSE_PKO", counter0_paymentParameter, lpuin_paymentParameter, kod_otdeleniyaParameter);
        }
    }
}
