//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLD_WORK
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<long> FIO_COUNTER { get; set; }
        public Nullable<int> FIO_LPUIN { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_SCOPE { get; set; }
        public string POST { get; set; }
        public string SCHEDULE { get; set; }
        public Nullable<int> HIRE_YEAR { get; set; }
        public Nullable<int> HIRE_MONTH { get; set; }
        public Nullable<int> HIRE_DAY { get; set; }
        public string CHIEF_SURNAME { get; set; }
        public string CHIEF_NAME { get; set; }
        public string CHIEF_SECNAME { get; set; }
        public string POST_INDEX { get; set; }
        public Nullable<short> AREA { get; set; }
        public Nullable<short> TER { get; set; }
        public Nullable<short> ORGN1 { get; set; }
        public Nullable<short> ORGN2 { get; set; }
        public Nullable<short> ORGN3 { get; set; }
        public Nullable<short> RAZDEL { get; set; }
        public string OKATO { get; set; }
        public Nullable<int> STREET { get; set; }
        public Nullable<short> HOUSE { get; set; }
        public string HOUSELITER { get; set; }
        public Nullable<byte> CORPUS { get; set; }
        public Nullable<short> FLAT { get; set; }
        public string FLATLITER { get; set; }
        public string FULLADR { get; set; }
        public string COMMENTADR { get; set; }
        public string PHONE_SECRETARY { get; set; }
        public string PHONE_WORK { get; set; }
        public string ORG_SITE { get; set; }
        public Nullable<int> SALARY { get; set; }
        public int EST_DOP_DOHOD { get; set; }
        public string BUSINESS_DESC { get; set; }
        public Nullable<int> BUSINESS_PROFIT { get; set; }
        public Nullable<int> PROPERTY_PROFIT { get; set; }
        public Nullable<int> PENSION { get; set; }
        public Nullable<int> BENEFIT { get; set; }
        public Nullable<int> OTHER_PROFIT { get; set; }
        public Nullable<int> GENERAL_FAMILY_PROFIT { get; set; }
        public Nullable<int> OBLIGATORY_PAYMENT { get; set; }
        public Nullable<byte> D_FIN_STATUS { get; set; }
    }
}
