//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLD_PLAN_REPORT
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public Nullable<byte> D_FIN_STATUS { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> SPOSOB { get; set; }
        public string SOOB { get; set; }
        public Nullable<long> DATA_COUNTER { get; set; }
        public Nullable<int> DATA_LPUIN { get; set; }
        public Nullable<long> FIO_COUNTER { get; set; }
        public Nullable<int> FIO_LPUIN { get; set; }
        public Nullable<int> CREDIT_ITEM_INDEX { get; set; }
        public Nullable<int> REZ { get; set; }
        public Nullable<System.DateTime> DATA_ZAV { get; set; }
        public Nullable<long> SERVICE_ID { get; set; }
        public Nullable<long> SMS_TEMPLATE_COUNTER { get; set; }
        public Nullable<int> SMS_TEMPLATE_LPUIN { get; set; }
        public string PHONE_MOBILE { get; set; }
        public Nullable<int> VR_OJID_SNYAT { get; set; }
    }
}
