//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLD_PAYMENT
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<int> ITEM_INDEX { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public Nullable<byte> D_FIN_STATUS { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<long> FIO_COUNTER { get; set; }
        public Nullable<int> FIO_LPUIN { get; set; }
        public Nullable<int> CREDIT_ITEM_INDEX { get; set; }
        public Nullable<System.DateTime> DATA_PLATEJA { get; set; }
        public Nullable<int> SUMMA_PLATEJA { get; set; }
        public Nullable<int> VID_PLATEJA { get; set; }
        public Nullable<int> CREDIT_BILL_BASIC_SUMM { get; set; }
        public Nullable<int> CREDIT_BILL_PERCENT { get; set; }
        public Nullable<int> CREDIT_BILL_PENALTY_PERCENT { get; set; }
        public Nullable<int> CREDIT_BILL_PENALTY_FIXED { get; set; }
        public string KOD_OTDELENIYA { get; set; }
        public Nullable<int> OPER_TYPE { get; set; }
        public Nullable<int> OPER_VID { get; set; }
        public string COMMENT { get; set; }
    }
}
