//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLD_ADDRESS
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<long> FIO_COUNTER { get; set; }
        public Nullable<int> FIO_LPUIN { get; set; }
        public string R_POST_INDEX { get; set; }
        public Nullable<short> R_AREA { get; set; }
        public Nullable<short> R_TER { get; set; }
        public Nullable<short> R_ORGN1 { get; set; }
        public Nullable<short> R_ORGN2 { get; set; }
        public Nullable<short> R_ORGN3 { get; set; }
        public Nullable<short> R_RAZDEL { get; set; }
        public string R_OKATO { get; set; }
        public Nullable<int> R_STREET { get; set; }
        public Nullable<short> R_HOUSE { get; set; }
        public string R_HOUSELITER { get; set; }
        public Nullable<byte> R_CORPUS { get; set; }
        public Nullable<short> R_FLAT { get; set; }
        public string R_FLATLITER { get; set; }
        public string R_FULLADR { get; set; }
        public string J_POST_INDEX { get; set; }
        public Nullable<short> J_AREA { get; set; }
        public Nullable<short> J_TER { get; set; }
        public Nullable<short> J_ORGN1 { get; set; }
        public Nullable<short> J_ORGN2 { get; set; }
        public Nullable<short> J_ORGN3 { get; set; }
        public Nullable<short> J_RAZDEL { get; set; }
        public string J_OKATO { get; set; }
        public Nullable<int> J_STREET { get; set; }
        public Nullable<short> J_HOUSE { get; set; }
        public string J_HOUSELITER { get; set; }
        public Nullable<byte> J_CORPUS { get; set; }
        public Nullable<short> J_FLAT { get; set; }
        public string J_FLATLITER { get; set; }
        public string J_FULLADR { get; set; }
        public int J_EQUALS_R { get; set; }
        public Nullable<byte> D_FIN_STATUS { get; set; }
    }
}
