//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLD_MEDICAL
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<long> FIO_COUNTER { get; set; }
        public Nullable<int> FIO_LPUIN { get; set; }
        public Nullable<byte> FAMILY_STATUS { get; set; }
        public Nullable<byte> FAMILY_COUNT { get; set; }
        public Nullable<byte> EDUCATION { get; set; }
        public string PHONE_HOME_R { get; set; }
        public string PHONE_HOME_J { get; set; }
        public string PHONE_MOBILE { get; set; }
        public string PROPERTY { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<byte> D_FIN_STATUS { get; set; }
        public Nullable<byte> DEPENDANT_COUNT { get; set; }
        public string TSEL_OF_ZAYM { get; set; }
        public string NAL_SUD { get; set; }
        public string NAL_KRED_OBYAZ { get; set; }
        public string COMMENT { get; set; }
        public int TEL_PROV { get; set; }
        public int SOGL_POL { get; set; }
        public int NOT_CALL { get; set; }
    }
}
