//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLM_CREDIT_TEMPLATE
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public Nullable<byte> D_FIN_STATUS { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<int> CODE { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> STAVKA_V_DEN { get; set; }
        public Nullable<decimal> PERCENT_PENALTY { get; set; }
        public Nullable<int> FIXED_PENALTY { get; set; }
        public Nullable<int> FLOATING_PENALTY { get; set; }
        public Nullable<int> FLOATING_PENALTY_DAY { get; set; }
        public Nullable<int> FLOATING_PENALTY_COUNT { get; set; }
        public Nullable<long> PROFILE_COUNTER { get; set; }
        public Nullable<long> PROFILE_LPUIN { get; set; }
        public Nullable<long> MINIMUM_DNEY { get; set; }
        public Nullable<decimal> POLNAYA_STOIM_ZAYMA { get; set; }
    }
}
