//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICROCREDIT.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLS_AK_SOST_ZAYM
    {
        public Nullable<long> COUNTER0 { get; set; }
        public int LPUIN { get; set; }
        public Nullable<int> ITEM_INDEX { get; set; }
        public Nullable<long> STATE { get; set; }
        public long COUNTER { get; set; }
        public Nullable<System.DateTime> D_START { get; set; }
        public Nullable<System.DateTime> D_MODIF { get; set; }
        public Nullable<System.DateTime> D_FIN { get; set; }
        public string OPERATOR { get; set; }
        public Nullable<long> FIO_COUNTER_CREDIT { get; set; }
        public Nullable<long> FIO_LPUIN_CREDIT { get; set; }
        public Nullable<int> ITEM_INDEX_CREDIT { get; set; }
        public Nullable<int> OSTATOK_PO_ZAYMU_1 { get; set; }
        public Nullable<int> OSTATOK_PO_OSNOVNOMU_DOLGU_1 { get; set; }
        public Nullable<int> OSTATOK_PO_OSNOVNOMU_PROTSENTU_1 { get; set; }
        public Nullable<int> OSTATOK_PO_PENI_1 { get; set; }
        public Nullable<int> OSTATOK_PO_SHTRAFU_1 { get; set; }
        public Nullable<int> OSTATOK_PO_SHTRAFU_ZA_DOSROCHNOE_POGASHENIE_1 { get; set; }
        public Nullable<System.DateTime> DATA_VOZVRATA_1 { get; set; }
        public Nullable<System.DateTime> DATA_ZAKRITIYA_1 { get; set; }
        public Nullable<int> STAT_1 { get; set; }
        public Nullable<int> OSTATOK_PO_ZAYMU_2 { get; set; }
        public Nullable<int> OSTATOK_PO_OSNOVNOMU_DOLGU_2 { get; set; }
        public Nullable<int> OSTATOK_PO_OSNOVNOMU_PROTSENTU_2 { get; set; }
        public Nullable<int> OSTATOK_PO_PENI_2 { get; set; }
        public Nullable<int> OSTATOK_PO_SHTRAFU_2 { get; set; }
        public Nullable<int> OSTATOK_PO_SHTRAFU_ZA_DOSROCHNOE_POGASHENIE_2 { get; set; }
        public Nullable<System.DateTime> DATA_VOZVRATA_2 { get; set; }
        public Nullable<System.DateTime> DATA_ZAKRITIYA_2 { get; set; }
        public Nullable<int> STAT_2 { get; set; }
    }
}
