mkdir d:\IT-MINDS\MICROCREDIT-WEB\BASES
mkdir d:\IT-MINDS\MICROCREDIT-WEB\BASES\CADTEX
mkdir d:\IT-MINDS\MICROCREDIT-WEB\BACKUP\CADTEX
mkdir d:\IT-MINDS\MICROCREDIT-WEB\PROGRAM
mkdir d:\IT-MINDS\MICROCREDIT-WEB\SQL
mkdir d:\IT-MINDS\MICROCREDIT-WEB\DOCS
mkdir d:\IT-MINDS\MICROCREDIT-WEB\DOCS\MODEL
mkdir d:\IT-MINDS\MICROCREDIT-WEB\DOCS\STRUCTURE